version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: mini-saas-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: mini_saas_ai
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

